name: GitHub Issue Notification to Slack
on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]
jobs:
  notifySlack:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL: 'C06RLL2PK7B'
    steps:
      - name: Notify Slack on Issue or Comment
        run: |
          if [ "${{ github.event_name }}" == "issues" ]; then
            PAYLOAD='{"channel":"'"$SLACK_CHANNEL"'","text":"'"${{ github.event.issue.html_url }}"'"}'
          elif [ "${{ github.event_name }}" == "issue_comment" ]; then
            PAYLOAD='{"channel":"'"$SLACK_CHANNEL"'","text":"'"${{ github.event.issue.html_url }}"'"}'
          fi

          curl -X POST -H 'Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}' -H 'Content-type: application/json; charset=utf-8' --data "$PAYLOAD" https://slack.com/api/chat.postMessage
